USE seo_service_db;

INSERT INTO pdp_seo_content (
  product_id, short_description, long_description, specifications, ingredients, nutrition,
  features, faqs, size_guide, regulatory_info, disclaimer, box_contents,
  meta_title, meta_description, meta_keywords, schema_json, images
) VALUES
(
  'AMZ-ECHO-001',
  'Smart speaker with premium sound and Alexa.',
  'Compact smart speaker for music, reminders, home control, and voice calling.',
  JSON_OBJECT('color','Charcoal','connectivity','Wi-Fi, Bluetooth','weight','940g'),
  NULL,
  NULL,
  JSON_ARRAY('Alexa enabled','Multi-room audio','Voice control'),
  JSON_ARRAY(JSON_OBJECT('q','Does it support Spotify?','a','Yes'), JSON_OBJECT('q','Can it control lights?','a','Yes, compatible devices required')),
  NULL,
  'BIS compliant for consumer electronics.',
  'Voice assistant responses may vary by region and service availability.',
  JSON_ARRAY('Echo Speaker','Power Adapter','Quick Start Guide'),
  'Buy Smart Speaker with Alexa | Fast Delivery',
  'Shop smart speaker with powerful audio and Alexa voice assistant.',
  'smart speaker,alexa speaker,home assistant',
  JSON_OBJECT('@context','https://schema.org','@type','Product','name','Smart Speaker'),
  JSON_ARRAY('https://example-cdn.com/images/echo-front.jpg','https://example-cdn.com/images/echo-side.jpg')
),
(
  'NYK-SHOE-042',
  'Men running shoes with responsive cushioning.',
  'Lightweight performance running shoes suitable for daily training and long runs.',
  JSON_OBJECT('material','Mesh','sole','Rubber','drop','10mm'),
  NULL,
  NULL,
  JSON_ARRAY('Breathable upper','Durable outsole','Comfort fit'),
  JSON_ARRAY(JSON_OBJECT('q','Are these true to size?','a','Yes, regular fit')), 
  'Refer size chart: UK 6-11 available.',
  'Imported and quality tested as per internal standards.',
  'Color shades may look different due to screen settings.',
  JSON_ARRAY('1 Pair Running Shoes'),
  'Men Running Shoes | Lightweight & Comfortable',
  'Order men running shoes with breathable mesh and long-lasting grip.',
  'running shoes,men shoes,sports shoes',
  JSON_OBJECT('@context','https://schema.org','@type','Product','name','Men Running Shoes'),
  JSON_ARRAY('https://example-cdn.com/images/shoe-top.jpg')
),
(
  'BBY-PROTEIN-310',
  'Whey protein blend for post-workout recovery.',
  'Chocolate-flavored whey protein powder with fast digesting proteins and amino acids.',
  JSON_OBJECT('flavor','Chocolate','servings','30','net_weight','1kg'),
  'Whey Protein Concentrate, Cocoa Powder, Lecithin, Sweetener.',
  JSON_OBJECT('protein_per_serving','24g','calories','130'),
  JSON_ARRAY('24g protein per scoop','Mixes easily','Great taste'),
  JSON_ARRAY(JSON_OBJECT('q','Is it vegetarian?','a','Yes')), 
  'Use scoop guide on label for accurate serving size.',
  'Manufactured in FSSAI registered facility.',
  'Not medical advice. Consult your physician if needed.',
  JSON_ARRAY('Protein Jar','Scoop'),
  'Whey Protein Powder 1kg | Chocolate Flavor',
  'Buy whey protein with 24g protein per serving for recovery and muscle support.',
  'whey protein,protein powder,post workout',
  JSON_OBJECT('@context','https://schema.org','@type','Product','name','Whey Protein Powder'),
  JSON_ARRAY('https://example-cdn.com/images/protein-jar.jpg')
)
ON DUPLICATE KEY UPDATE
  short_description = VALUES(short_description),
  long_description = VALUES(long_description),
  specifications = VALUES(specifications),
  ingredients = VALUES(ingredients),
  nutrition = VALUES(nutrition),
  features = VALUES(features),
  faqs = VALUES(faqs),
  size_guide = VALUES(size_guide),
  regulatory_info = VALUES(regulatory_info),
  disclaimer = VALUES(disclaimer),
  box_contents = VALUES(box_contents),
  meta_title = VALUES(meta_title),
  meta_description = VALUES(meta_description),
  meta_keywords = VALUES(meta_keywords),
  schema_json = VALUES(schema_json),
  images = VALUES(images);
